name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
          - os: ubuntu-24.04-arm
          - os: windows-latest
          - os: windows-11-arm

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - name: Setup lde
        uses: lde-org/setup-lde@master
        with:
          version: nightly

      - name: Install tools for tests
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y xvfb x11-utils xsel

      - name: Run tests (Linux)
        if: runner.os == 'Linux'
        run: xvfb-run lde test

      - name: Run tests (Windows)
        if: runner.os == 'Windows'
        run: lde test
